# Generated by Django 3.2.25 on 2025-12-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
