# Generated by Django 3.2.25 on 2025-12-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20251223_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
