# Generated by Django 3.2.25 on 2025-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20251223_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('reel', 'Reel'), ('carousel', 'Carousel'), ('static', 'Static Post'), ('story', 'Story'), ('video', 'Video'), ('photo', 'Photo')], max_length=20),
        ),
    ]
