# Generated by Django 3.2.25 on 2025-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20251223_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails/'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='BestTimeToPost',
        ),
    ]
