# Generated by Django 3.2.25 on 2025-12-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20251223_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='local_image',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BestTimeToPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('hour', models.IntegerField()),
                ('avg_engagement', models.FloatField()),
                ('post_count', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.socialaccount')),
            ],
            options={
                'unique_together': {('account', 'day_of_week', 'hour')},
            },
        ),
    ]
